### ISSUE TITLE
Missing calib.object and calib.grasps 

### ISSUE THREAD

**Issue by ZhaoLizz** [brown-ivl/manus#10]
The camera parameters file `calib.object/optim_params.txt` contained in the small batch example dataset, but not contained in the main dataset. Are these two files the same?

So does the `calib.grasps//optim_params.txt`.

**Comment by coreqode** [comment]
Umm yes. For object and grasp, it should be similar. But for hand it would be difficult. Also I have uploaded new version of dataset in `AnnotationsV1` folder in the same s3 bucket. So please consider using that. That will have all the missing part.

**Comment by ZhaoLizz** [comment]
Thanks for your time and help! I will check it later.
