### ISSUE TITLE
camera info

### ISSUE THREAD

**Issue by leozhangchina** [brown-ivl/manus#12]
Hello! I've been studying your dataset and has encountered yet another problem on the extrinsic parameters of the cameras provided in the hdf5 file. When I tried to reconstruct the scene in the blender tool, the cameras don't seem to be facing the same spot. Is it due to the differences in coordinate systems or do you have a script for coordinate transformation? Any help or information would be appreciated, thank you!

**Comment by coreqode** [comment]
Hi!. I have uploaded a visualization script using Open3D for cameras [here](https://github.com/brown-ivl/manus/blob/main/scripts/dataset_helpers/vis_cameras.py). Hope this helps.
