### ISSUE TITLE
InterHand train/test split

### ISSUE THREAD

**Issue by yilan120** [brown-ivl/manus#13]
Thanks so much for this valuable work and dataset!

I noticed in your paper that you also evaluated your method on the InterHand Dataset. I was wondering if you could provide more details about the specific data splitting strategy you used, or if there is any code available.

Thank you in advance!

**Comment by coreqode** [comment]
Thanks for showing interest in our work. We used the following frames for validation in Interhand dataset
[val_split_cap0.json](https://github.com/user-attachments/files/17883147/val_split_cap0.json)
[val_split_cap1.json](https://github.com/user-attachments/files/17883148/val_split_cap1.json)
