### ISSUE TITLE
Where can I find the canonical hand parameters?

### ISSUE THREAD

**Issue by ACondaway** [brown-ivl/manus#14]
Hi,
I really appreciate your work, but I am wondering where I can find how you set up the hand pose in canonical space using MANUS or MANO.

**Comment by coreqode** [comment]
Hi! Thanks for showing interest in our work. We automatically generate the blend file for each subject based on the bone length (estimated from 3D key points). I have uploaded the blend files for the rest poses for each subject [here](https://github.com/brown-ivl/manus/tree/main/data/rest_poses)
