### ISSUE TITLE
missing files and partial annotations in the dataset

### ISSUE THREAD

**Issue by aidilayce** [brown-ivl/manus#15]
Hello,

Thank you for the great work! I have downloaded the dataset using the commands given in Dataset.md. However, `bone_keypoints.ply`, `bone_lens.json` and `rest_keypts.ply` are missing from each subject folder, and only `subject0` and `subject1` have annotations while `subject2` and `subject3` have only `grasps/` folder. 

Could you please verify if these files and annotations are expected to be missing or if there is an issue with the dataset upload?

**Comment by coreqode** [comment]
Hi! Thanks for letting us know. 
- I have uploaded annotations for `subject2` as well. We don't have annotations for `subject3` and only have raw videos, as pose estimation didn't work for the gloved hand. 
- There is no need for `bone_keypoints.ply, bone_lens.json and rest_keypoints.ply` as they are used in pre-processing of data only.

**Comment by ZhaoLizz** [comment]
@coreqode 
Hi! Thanks for the great work! It seems that annotations for `subject2/grasps` are still missing. There are only `bboxes` and `keypoints_2d` folders. Can you upload these missing annotations? Thank you in advance! 

`aws s3 ls s3://manus-data/annotationsV1/subject2/grasps/color2_grasp1/pose_dumps/ --no-sign-request`
```
                           PRE bboxes/
                           PRE keypoints_2d/
```
