### ISSUE TITLE
Blender Dependencies

### ISSUE THREAD

**Issue by Dennis-Perrett** [brown-ivl/manus#2]
Hi,

I've been trying to get this up and running, but I notice that the blender scripts are dependent on blender_wormholes. I pulled your the repo, but it would appear that there are some pending updates, namely Object.set_origin_to().

Is it possible to get these uploaded either here or as part of the blender_wormholes repo?

Cheers

**Comment by coreqode** [comment]
Hi Dennis, could you please install `blender-wormholes` as `pip install blender-wormholes`? This should fix the blender errors.
