### ISSUE TITLE
how to acquire novel_cam.pkl

### ISSUE THREAD

**Issue by leozhangchina** [brown-ivl/manus#6]

**Comment by coreqode** [comment]
https://github.com/brown-ivl/manus/blob/58b4eab5f8442bfb9f6a9631508879132723c591/scripts/train/run_composite.sh#L25

This part of code is used to generate `novel_cam.pkl` file.

**Comment by leozhangchina** [comment]
this is but a executable blender software, do I need to generate the cams myself?

**Comment by coreqode** [comment]
Yeah. Cams are generated using blender script automatically using the fitted gaussians.
