### ISSUE TITLE
Missing data in MANUS-Grasps Dataset, no mesh in other objects.

### ISSUE THREAD

**Issue by leozhangchina** [brown-ivl/manus#7]
There's no ngp_mesh in any other object folders except the small batch provided, making it impossible to sample gaussian. Can I skip the step or acquire the data elsewhere? Any help would be appreciated, thank you, marvellous work!

**Comment by coreqode** [comment]
Thanks for pointing this out. I have updated the dataset now. Let me know, if you find any other bugs/issues.

**Comment by ElectronicElephant** [comment]
Hi @coreqode ,

Thanks for your effort! I am just wondering if the updated dataset is in this path: `s3://manus-data/annotationsV1` ?

**Comment by coreqode** [comment]
Oh yeah correct. I forget to update you about this. I will update the README.md file
