### ISSUE TITLE
Missing 4th channel in refined segments.

### ISSUE THREAD

**Issue by leozhangchina** [brown-ivl/manus#8]
Hello! As for the refined segments provided in the dataset, I noticed that there's no transparency channel. Therefore, I am unable to mask the background. Any help would be appreciated, thank you!

**Comment by coreqode** [comment]
Thanks for pointing this out. I might have overwritten the original segmentation masks. I have updated the AWS link.

**Comment by leozhangchina** [comment]
thank you for the update, I will check on your fancinating dataset!
